sonar.projectKey=Varelaso32_reservas-laboratorios-frontend
sonar.organization=varelaso32
sonar.projectName=reservas-laboratorios-frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts
